### ISSUE TITLE
Checkpoint side-effect deleting last record

### ISSUE THREAD

**Issue by nikostoulas** [rclark/kinesis-readable#2]
Hi there,
popping an element out of the records array to get the sequence number affects the records array in read.
So if async work happens in there, the last record will be lost.

Thanks

**Comment by rclark** [comment]
Good point! This should've been adjusted when I [changed to pushing arrays of records](https://github.com/rclark/kinesis-readable/commit/e9412013dbd2847806ae60be06cb25174711e104) (not individually) into to stream. I'll get to fixing this today.
