### ISSUE TITLE
Getting ProvisionedThroughputExceededException error

### ISSUE THREAD

**Issue by d3netxer** [rclark/kinesis-readable#4]
I am seeing this on my code on my Amazon EC2 server, which is a lot faster than when I test it locally and don't see this error as much

{ [ProvisionedThroughputExceededException: Rate exceeded for shard shardId-000000000000 in stream xxxxxx under account xxxxxxxxx.]
  message: 'Rate exceeded for shard shardId-000000000000 in stream xxxxxx under account xxxxxxxxxxxx.',
  code: 'ProvisionedThroughputExceededException',
  time: Mon Nov 16 2015 15:56:50 GMT+0000 (UTC),
  statusCode: 400,
  retryable: true }

Any way to fix this?

**Comment by rclark** [comment]
There is a limit to how fast you can read data from Kinesis. [From the docs](http://docs.aws.amazon.com/kinesis/latest/dev/service-sizes-and-limits.html):

> Each shard can support up to 5 transactions per second for reads, up to a maximum total data read rate of 2 MB per second.

Do you have any guess which of these limits you're hitting? Are your records large enough that you may be reading > 2MB per second? 

That said, this library doesn't implement any kind of rate limiting on reads, and it should.

**Comment by d3netxer** [comment]
let's say about 150kb per record, but it can actually be very variable.

Also, I'm not sure how many transactions are occurring per second.

I'm new to Kenesis, so I'm not exactly sure how I can get past this error. I'm pretty sure it is because one of the two reasons you mention. I can't think of what else it can be.

**Comment by d3netxer** [comment]
I'm guessing my EC2 instance is doing more transactions per second than my local machine, does that sounds right?

**Comment by rclark** [comment]
> my EC2 instance is doing more transactions per second than my local machine

Yes, the I/O between an EC2 and a Kinesis stream is likely to be quite a bit faster than from your local machine to Kinesis.

The only way to get past this is to limit the rate that the kinesis-readable stream makes `GetRecords` requests. This is what I meant when I said that this library needs to implement some sort of rate limiting.

**Comment by kamicut** [comment]
@rclark what I did temporarily is add a `setTimeout` instead of `setImmediate` here https://github.com/rclark/kinesis-readable/blob/master/index.js#L80
