### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by eridal** [rclark/kinesis-readable#6]
Hi,

We are looking for different options to replace the amazon kcl-library.

This project has a nice api and we have some questions regarding the current state of the project.

- Can it allow to `N` clients concurrently consuming from `M` shards?

- Does the checkpoints work the same as the kcl library?

Many thanks in advance,

**Comment by rclark** [comment]
Hi there -- sorry for the long delay. This library is only capable of reading from 1 shard at a time, and does not implement a backend that "remembers" checkpoints in any fashion. 

It could be used as a piece of a system that replaces the kcl library, but does not do so on its own. You may want to have a look at https://github.com/mapbox/kine.
